Algoritmo "26"
// Lógica de Programação
// Robson D. Preuss
// 07/06/2021
// Gh Branding
Var
   n1, n2: inteiro

Inicio
   Escreval("Digite o primeiro Número: ")
   Leia(n1)

   Escreval("Digite o segundo Número: ")
   Leia(n2)

   Se n1 = n2 entao
      Escreva("Não existe valor maior, os dois são iguais")
   senao
      se n1 > n2 entao
         Escreva("O primeiro valor é o maior")
      senao
         Escreva("O segundo valor é o maior")
      fimse
   fimse
Fimalgoritmo