Algoritmo "48"
// Lógica de Programação
// Robson D. Preuss
// 07/06/2021
// Gh Branding
Var
   Contador, Soma, Numero:Inteiro

Inicio
      Contador <- 1
      Enquanto Contador <= 7 faca
      Escreva("Digite o",Contador,"o. número: ")
      Leia(Numero)

      Soma <- Soma + Numero
      Contador <- Contador + 1
      Fimenquanto
      
      Escreva("A soma dos números é:",Soma)


Fimalgoritmo